export const FETCH_COORDINATES = "FETCH_COORDINATES";
export const FETCH_COORDINATES_SUCCESS = "FETCH_COORDINATES_SUCCESS";
export const FETCH_COORDINATES_FAILURE = "FETCH_COORDINATES_FAILURE";
export const FETCH_FROM_API = "FETCH_FROM_API";
export const TEMP_TO_FAHRENHEIT = "TEMP_TO_FAHRENHEIT";
export const TEMP_TO_CELSIUS = "TEMP_TO_CELSIUS";
export const TOGGLE_CELSIUS = "TOGGLE_CELSIUS";
