export const FETCH_COORDINATES = "FETCH_COORDINATES";
export const FETCH_COORDINATES_SUCCESS = "FETCH_COORDINATES_SUCCESS";
export const FETCH_COORDINATES_FAILURE = "FETCH_COORDINATES_FAILURE";
export const FETCH_FROM_API = "FETCH_FROM_API";
export const TOGGLE_CELSIUS = "TOGGLE_CELSIUS";
